#!/usr/bin/env ruby

file = '.go.cov'
exclude = File.exist?(file) ? File.read(file).split.join('|') : '.pb|main.go'

Dir['test/reports/*.cov'].each do |f|
  nf = "#{File.dirname(f)}/#{File.basename(f, File.extname(f))}-new#{File.extname(f)}"

  File.open(nf, 'w') do |out_file|
    File.foreach(f) do |line|
      out_file.puts line unless line =~ /(#{exclude})/
    end
  end
end

files = Dir['test/reports/*-new.cov'].join(' ')

`gocovmerge #{files} > test/reports/final.cov && rm -f #{files}`
