#!/usr/bin/env bash
# Filter the main Go coverage profile into the final report profile.

set -eo pipefail

if [ -f .gocov ]; then
  cov=$(cat .gocov)
else
  cov="test"
fi

grep -Ev "${cov}" test/reports/profile.cov >test/reports/final.cov
