#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

file = '.gocov'
exclude = File.exist?(file) ? File.read(file).strip : 'test|.pb|main.go'
path = 'test/reports/filter'

FileUtils.mkdir_p path

Dir['test/reports/*.cov'].each do |f|
  filter_file = File.join(path, File.basename(f))

  File.open(filter_file, 'w') do |out_file|
    File.foreach(f) do |line|
      out_file.puts line unless line =~ /(#{exclude})/
    end
  end
end

# https://github.com/alexfalkowski/gocovmerge
cmd = "gocovmerge -d #{path} -o test/reports/final.cov"
pid = spawn({}, cmd, %i[out err] => [File.join(path, 'gocovmerge.log'), 'a'])

Process.waitpid2 pid
FileUtils.rmdir path
