#!/usr/bin/env bash
# shellcheck disable=SC1091
# Open a Go profile from test/reports after validating profile components.

set -eo pipefail

readonly profile="$1"
shift

source "$(dirname "$0")/../../lib/validate.sh"
validate_profile "$@"

go tool pprof "test/reports/$profile"
