#!/usr/bin/env bash

set -euxo pipefail

readonly feature="$1"
readonly tags="$2"

if [ -n "$tags" ]; then
  bundler exec cucumber --profile report $feature --tags "$tags"
else
  bundler exec cucumber --profile report $feature
fi
