#!/usr/bin/env bash

set -eo pipefail

readonly feature="$1"
readonly tags="$2"

args=(--profile report)

if [ -n "$feature" ]; then
  args+=("$feature")
fi

args+=(--tags "not @benchmark")

if [ -n "$tags" ]; then
  args+=(--tags "$tags")
fi

COVERAGE_NAME=features bundler exec cucumber "${args[@]}"
