#!/usr/bin/env bash
# shellcheck disable=SC2086

set -eo pipefail

readonly feature="$1"
readonly tags="$2"

if [ -n "$tags" ]; then
  COVERAGE_NAME=features bundler exec cucumber --profile report $feature --tags "not @benchmark" --tags $tags
else
  COVERAGE_NAME=features bundler exec cucumber --profile report $feature --tags "not @benchmark"
fi
